#!/usr/bin/env fish

git submodule update --recursive --remote

set initial_dir (pwd)
for dir in modules/*/
    if test -d "$dir"
        cd "$dir"
        echo -n "$dir "
        git pull
        cd $initial_dir
    end
end
cd $initial_dir
